In [41]:
import numpy as np

In [42]:
#1.Create a numpy array arr of integers from 0 to 5 and print its datatype.
arr = np.array([0, 1, 2, 3, 4, 5])
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int32


In [43]:
#2.Given a numpy array arr,check if its datatype is float64.
arr = np.array([1.0, 2.0, 3.0])
if arr.dtype == np.float64:
    print("The array is of type float64.")
else:
    print("The array is NOT of type float64.")

The array is of type float64.


In [44]:
#3.Create a numpy array arr with a datatype of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j],dtype=np.complex128)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [45]:
#4.Convert an existing numpy array arr of integers to float32 datatype.
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print("Converted array:", arr_float32)
print("Data type:", arr_float32.dtype)

Converted array: [1. 2. 3. 4. 5.]
Data type: float32


In [46]:
#5.Given a numpy array arr with float64 datatype,convert it to float32 to reduce decimal precision.
arr = np.array([1.123456789, 2.987654321, 3.1415926535], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("Original array (float64):", arr)
print("Converted array (float32):", arr_float32)
print("New data type:", arr_float32.dtype)

Original array (float64): [1.12345679 2.98765432 3.14159265]
Converted array (float32): [1.1234568 2.9876542 3.1415927]
New data type: float32


In [47]:
#6.Write a function array_attributes that takes a numpy array as input and return its shape ,size,and datatype.
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])

Shape: (2, 3)
Size: 6
Data type: int32


In [48]:
#7.Create a function array_dimension that returns the dimensionality of a numpy array.
def array_dimension(arr):
    return arr.ndim
arr = np.array([[1, 2, 3],[4,5,6]])
dim = array_dimension(arr)
print("Dimensionality:", dim)

Dimensionality: 2


In [49]:
#8.Design a function item_stride_relationship that returns the shape and strides of the given array.
def item_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = item_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (12, 4)


In [50]:
#9.Create a function array_strides that returns the strides of the given NumPy array.
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2], [3, 4]])
print("Strides:", array_strides(arr))

Strides: (8, 4)


In [51]:
#10.Design a function shape_stride_relationship that returns the shape and strides of the given array. 
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1, 2], [3, 4]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 2)
Strides: (8, 4)


In [52]:
#11.Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)
print("Zeros array:", create_zeros_array(5))

Zeros array: [0. 0. 0. 0. 0.]


In [53]:
#12.Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def com(rows, cols):
    return np.ones((rows, cols))
print(com(2, 3))

[[1. 1. 1.]
 [1. 1. 1.]]


In [54]:
#13.Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.
def gna(start, stop, step):
    return np.arange(start, stop, step)
print("Range array:", gna(0, 10, 2))

Range array: [0 2 4 6 8]


In [55]:
#14.Design a function generate_linear_space(start, stop, num) for equally spaced values.
def gls(start, stop, num):
    return np.linspace(start, stop, num)
print("Linear space:", gls(0, 1, 5))

Linear space: [0.   0.25 0.5  0.75 1.  ]


In [56]:
#15.Create a function create_identity_matrix(n) using numpy.eye.
def cim(n):
    return np.eye(n)
print("Identity matrix:",cim(4))

Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
#16.Write a function that converts a Python list into a NumPy array. 
def list_to_numpy_array(lst):
    return np.array(lst)
my_list = [1, 2, 3, 4, 5]
print("NumPy array:", list_to_numpy_array(my_list))

NumPy array: [1 2 3 4 5]


In [58]:
#17.Create a NumPy array and use numpy.view() to create a new view with the same data.
def create_view(arr):
    return arr.view()
original_arr = np.array([10, 20, 30, 40])
view_arr = create_view(original_arr)
print("Original array:", original_arr)
print("View array:", view_arr)
view_arr[0] = 999
print("Modified original array:", original_arr)
print("Modified view array:", view_arr)


Original array: [10 20 30 40]
View array: [10 20 30 40]
Modified original array: [999  20  30  40]
Modified view array: [999  20  30  40]


In [60]:
#18.Write a function  to concatenate two numpy arrays along a specified axis.
def con_arr(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Concatenate along axis 0:\n", con_arr(a, b, axis=0))
print("Concatenate along axis 1:\n", con_arr(a, b, axis=1))

Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [61]:
#19.Concatenate two arrays with different shapes horizontally using numpy.concatenate.
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10]])
result = np.concatenate((arr1, arr2), axis=1)
print("Concatenated array:\n", result)
print("Shape:", result.shape)

Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
Shape: (2, 5)


In [63]:
#20.Vertically stack multiple arrays from a list using numpy.vstack.
def vertical_stack(arr_list):
    return np.vstack(arr_list)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arrays = [arr1, arr2, arr3]
result = vertical_stack(arrays)
print("Vertically stacked array:\n", result)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
#21.write a function to generate an array of integers within a specified range(inclusive with a sharp).
def generate_inclusive_range(start, stop):
    return np.arange(start, stop + 1)
arr = generate_inclusive_range(3, 8)
print(arr)

[3 4 5 6 7 8]


In [65]:
#22.Generate 10 equally spaced values between 0 and 1 using numpy.1
arr = np.linspace(0, 1, 10)
print("Equally spaced values:", arr)

Equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [66]:
#23.Create 5 logarithmically spaced values between 1 to 1000.
arr = np.logspace(start=0, stop=3, num=5)
print("Logarithmically spaced values:", arr)

Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [74]:
#24.Write a function to replace all negative values in a specific column with zeros using NumPy.
def replace_negatives_in_column(arr, col_index):
    arr = arr.copy() 
    arr[arr[:, col_index] < 0, col_index] = 0
    return arr
data = np.array([[ 5, -3,  7],
                 [-1,  2, -6],
                 [ 4, -8,  9]])
result = replace_negatives_in_column(data, 1)
print("Modified array:\n", result)

Modified array:
 [[ 5  0  7]
 [-1  2 -6]
 [ 4  0  9]]


In [69]:
#26.Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print("3rd element:", third_element)

3rd element: 30


In [68]:
#27.Retrieve the element at index (1, 2) from a 2D array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print("Element at (1, 2):", element)

Element at (1, 2): 6


In [70]:
#28.Extract elements greater than 5 using boolean indexing.
arr = np.array([1, 6, 3, 8, 5, 9])
greater_than_5 = arr[arr > 5]
print("Elements greater than 5:", greater_than_5)

Elements greater than 5: [6 8 9]


In [71]:
#29.Slice elements from index 2 to 5 (inclusive) from a NumPy array.
arr = np.array([10, 20, 30, 40, 50, 60, 70])
sliced = arr[2:6]
print("Sliced elements (index 2 to 5):", sliced)

Sliced elements (index 2 to 5): [30 40 50 60]


In [72]:
#30.Slice the sub array [[2,3],[5,6]] from a 2D array.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
sub_array = arr[0:2, 1:3]
print("Sub-array:\n", sub_array)

Sub-array:
 [[2 3]
 [5 6]]


In [75]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
to_add = np.array([[100, 200, 300]])
result = arr + to_add
print("Result of broadcasting addition:\n", result)

Result of broadcasting addition:
 [[101 202 303]
 [104 205 306]
 [107 208 309]
 [110 211 312]]


In [76]:
a = np.array([[1], [2], [3]])
b = np.array([[10, 20, 30]])
result = a + b
print("Result of adding (3,1) and (1,3):\n", result)

Result of adding (3,1) and (1,3):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [77]:
a = np.random.rand(2, 3)
b = np.random.rand(2, 2)
if a.shape == b.shape:
    result = a * b
else:
    print("Shapes are incompatible for element-wise multiplication:", a.shape, b.shape)

Shapes are incompatible for element-wise multiplication: (2, 3) (2, 2)


In [78]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
col_mean = np.mean(arr, axis=0)
print("Column-wise mean:", col_mean)

Column-wise mean: [4. 5. 6.]


In [79]:
row_max = np.max(arr, axis=1)
print("Row-wise maximums:", row_max)

Row-wise maximums: [3 6 9]


In [80]:
col_max_indices = np.argmax(arr, axis=0)
print("Indices of max in each column:", col_max_indices)

Indices of max in each column: [2 2 2]


In [81]:
def moving_sum_1d(arr, window_size):
    return np.convolve(arr, np.ones(window_size, dtype=int), mode='valid')
def moving_sum_rows(arr, window_size):
    return np.array([moving_sum_1d(row, window_size) for row in arr])
arr = np.array([[1, 2, 3, 4, 5],
                [10, 20, 30, 40, 50]])
result = moving_sum_rows(arr, window_size=3)
print("Moving sum along rows:\n", result)

Moving sum along rows:
 [[  6   9  12]
 [ 60  90 120]]


In [82]:
arr = np.array([[2, 4, 6],
                [8, 10, 12],
                [14, 16, 18]])
are_all_even = np.all(arr % 2 == 0, axis=0)
print("All elements even in each column:", are_all_even)

All elements even in each column: [ True  True  True]


In [83]:
arr = np.array(["apple pie", "banana pie", "cherry tart", "apple tart"])
count = np.char.count(arr, "pie")
print("Occurrences of 'pie':", count)

Occurrences of 'pie': [1 1 0 0]


In [84]:
arr = np.array(["Hello", "WORLD", "NumPy", "123ABC"])
uppercase = np.array([''.join([c for c in s if c.isupper()]) for s in arr])
print("Uppercase characters:", uppercase)

Uppercase characters: ['H' 'WORLD' 'NP' 'ABC']


In [85]:
arr = np.array(["hello world", "python world", "world of data"])
replaced = np.char.replace(arr, "world", "universe")
print("Replaced strings:", replaced)

Replaced strings: ['hello universe' 'python universe' 'universe of data']


In [86]:
arr1 = np.array(["good", "data", "Num"])
arr2 = np.array(["bye", "science", "Py"])
concatenated = np.char.add(arr1, arr2)
print("Element-wise concatenation:", concatenated)

Element-wise concatenation: ['goodbye' 'datascience' 'NumPy']


In [87]:
arr = np.array(["apple", "banana", "cherry", "date"])
lengths = np.char.str_len(arr)
max_length = lengths.max()
print("Length of the longest string:", max_length)

Length of the longest string: 6


In [88]:
arr = np.random.randint(1, 1001, size=100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_dev}")

Mean: 519.08
Median: 489.0
Variance: 74834.35359999999
Standard Deviation: 273.55868401496593


In [89]:
arr = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

25th Percentile: 21.25
75th Percentile: 75.5


In [90]:
x = np.random.rand(50)
y = np.random.rand(50)
corr_matrix = np.corrcoef(x, y)
corr_coef = corr_matrix[0, 1]
print(f"Correlation coefficient: {corr_coef}")

Correlation coefficient: 0.022362338249466443


In [91]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[19 22]
 [43 50]]


In [92]:
arr = np.random.randint(1, 101, size=50)
percentiles = np.percentile(arr, [10, 50, 90])
quartiles = np.percentile(arr, [25, 50, 75])
print(f"10th, 50th, 90th percentiles: {percentiles}")
print(f"Quartiles (25th, 50th, 75th): {quartiles}")

10th, 50th, 90th percentiles: [ 5.  41.  81.3]
Quartiles (25th, 50th, 75th): [18.5  41.   71.75]


In [95]:
element = 25
indices = np.where(arr == element)[0]
if indices.size > 0:
    index = indices[0]
else:
    index = -1  # Not found
print(f"Index of {element}: {index}")

Index of 25: 15


In [96]:
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

Sorted array: [ 1  2  3  4  5  5  5  6  7  9 11 15 18 20 25 26 27 28 30 33 34 34 35 35
 40 42 42 44 45 45 46 49 51 54 54 64 65 74 74 75 75 75 76 77 81 84 87 91
 95 99]


In [97]:
greater_than_20 = arr[arr > 20]
print("Elements greater than 20:", greater_than_20)

Elements greater than 20: [34 35 46 75 28 54 30 45 44 75 33 54 91 25 26 64 42 34 27 74 95 84 75 81
 74 45 51 42 40 35 49 99 77 87 65 76]


In [98]:
divisible_by_3 = arr[arr % 3 == 0]
print("Elements divisible by 3:", divisible_by_3)

Elements divisible by 3: [75 54 30 45 75 33 54 42 27  6 15 84 75 81 45  9 51 42 18  3 99 87]


In [99]:
between_20_and_40 = arr[(arr >= 20) & (arr <= 40)]
print("Elements between 20 and 40:", between_20_and_40)

Elements between 20 and 40: [20 34 35 28 30 33 25 26 34 27 40 35]


In [100]:
byte_order = arr.dtype.byteorder
print(f"Original byte order: {byte_order}")

Original byte order: =


In [101]:
arr.byteswap(inplace=True)
print("Array after byte swapping:", arr)
print(f"Byte order after byteswap: {arr.dtype.byteorder}")

Array after byte swapping: [ 335544320  570425344  587202560   83886080  771751936 1258291200
  469762048  905969664  503316480  754974720  738197504 1258291200
  553648128  905969664 1526726656  419430400  184549376  436207616
 1073741824  704643072  570425344  452984832  100663296 1241513984
  251658240 1593835520 1409286144   67108864 1258291200   16777216
 1358954496   33554432 1241513984  754974720  150994944  855638016
  704643072  671088640  587202560  822083584  301989888   83886080
  117440512   83886080   50331648 1660944384 1291845632 1459617792
 1090519040 1275068416]
Byte order after byteswap: =
